spring.application.name=Edu-Assist

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/projectdb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.allowed.domain=ges-coengg.org
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

google.client.id=${GOOGLE_CLIENT_ID:355258604701-a4s7p6ubrfjhec26tq1ddadsh218emdk.apps.googleusercontent.com}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:mahekshaikh9767@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:vehv wxhh bkxl tfar}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.otp.expiry-minutes=5
app.mail.from=${SPRING_MAIL_USERNAME:mahekshaikh9767@gmail.com}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}